python-targets:
    - 3
pep8:
  full: true
doc-warnings: yes
test-warnings: no
strictness: veryhigh
max-line-length: 120
uses:
    - docopt
autodetect: yes
requirements:
    - requirements.txt
ignore-paths:
    - docs
    - mypackage/vendor
ignore-patterns:
    - ^example/doc_.*\.py$
    - (^|/)docs(/|$)
