language: python

os:
  - linux

python:
  - "3.4"
  - "3.5"

install:
  - pip install --upgrade pip
  - pip install setuptools
  - pip install --upgrade setuptools
  - pip install coveralls
  - pip install -e .
  - pip list

script:
  - ls
  - python setup.py test
  - coverage run --source=slackapi.py setup.py test
  - ls -all
  - cat .coverage


after_success: coveralls
