language: python

os:
  - linux

python:
  - "3.4"
  - "3.5"

install:
  - pip install --upgrade pip
  - pip install setuptools
  - pip install --upgrade setuptools
  - pip install coveralls
  - pip install -e .
  - pip list

script:
  - python setup.py test
  - coverage run --source="slackapi.py,sls.py,scmd.py,utils.py" setup.py test

after_success: coveralls

