language: python

os:
  - linux

python:
  - "3.4"
  - "3.5"

install:
  - pip install --upgrade pip
  - pip install setuptools
  - pip install --upgrade setuptools
  - pip install coveralls
  - pip install -e .
  - pip list

script:
  - python setup.py test
  - coverage run --source="slackapi.py,sls.py,scmd.py,utils.py" setup.py test

after_success: coveralls

deploy:
  provider: pypi
  user: nicola.coretti
  password:
    secure: "YDHPqen5YNYHajfiDARogRQ1wgI1wgf+woXkX3CmOI8/XzIH0RykONlQ5fkntyZ3lgNlxPPg5UKy1xQvF/FFKrRY+8LnVXavpdZBuo3DlYpHNg3SchrVXB8teC1fyUDQcsKSXC/MTN4TlTwpjeKl6f7iIm/3qNslmGFqCLL1XKJial9U0tr1dhcmVEn+vukQP/aJY39n5KCPn3GpUiWY45S3g7kwE3+S6lmdHwLW0zcFIvLja08562jWxC118EhQuWuUdCBYGLTZkqq28R2BfX26fW4nqE5poEGYnvtlFiYRV1MtnnO+8dvT1vQ1n2qbfniaARH1Xi1U350t6nQcZZ0xAk8tyN9bhu4STvDng3ZLiZFlO0CzNtZhSMeElzNkZL5wkGSQEMgB24AgIW93E4M9jYoAhbXtsebt+SyJDxo5eTYB6HjcF+yulKmeHpkrN5MNKLyOeJeSEBtID+WICRedrkMmH+Nq4IAqi0dcER9llKHb29EL6ZE9EgA7jgFG2DFgvyMTnk85ryACfKciQ55bpKGrp7+9MEjM+J7XHtQyOpTBEFkeYVpxka+CRZVsmnD2WdLjawRQ9/DWoR4jglDPqDWNw8OE7PUTG63nC2OYrUJEb7KDdKoLIBxGCWKP4bZhlaDjNicTln04g4hmQFOHmTARpZ42jY1N1tIaF5M="
  on:
    tags: true

